# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Big_Num_Logical_Operation.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(666, 519)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgba(0,52,48,230);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setStyleSheet("border-radius: 10px;\n"
"border: 3px solid rgb(230, 231, 197);\n"
"background-color: rgb(255, 255, 255);")
        self.textEdit_3.setObjectName("textEdit_3")
        self.horizontalLayout.addWidget(self.textEdit_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setStyleSheet("border-radius: 10px;\n"
"border: 3px solid rgb(230, 231, 197);\n"
"background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_2.addWidget(self.textEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(175, 30))
        self.pushButton_5.setMaximumSize(QtCore.QSize(250, 60))
        self.pushButton_5.setStyleSheet("#pushButton_5{\n"
"background-color: rgb(230, 231, 197);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#pushButton_5:hover{\n"
"border: 1px solid rgb(230, 231, 197);\n"
"border-radius: 10px;\n"
"background-color: rgb(72, 81, 62);\n"
"color:rgb(255, 255, 255);\n"
"\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setMinimumSize(QtCore.QSize(175, 30))
        self.pushButton_7.setMaximumSize(QtCore.QSize(250, 60))
        self.pushButton_7.setStyleSheet("#pushButton_7{\n"
"background-color: rgb(230, 231, 197);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#pushButton_7:hover{\n"
"border: 1px solid rgb(230, 231, 197);\n"
"border-radius: 10px;\n"
"background-color: rgb(72, 81, 62);\n"
"color:rgb(255, 255, 255);\n"
"\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_3.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setMinimumSize(QtCore.QSize(175, 30))
        self.pushButton_8.setMaximumSize(QtCore.QSize(250, 60))
        self.pushButton_8.setStyleSheet("#pushButton_8{\n"
"background-color: rgb(230, 231, 197);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#pushButton_8:hover{\n"
"border: 1px solid rgb(230, 231, 197);\n"
"border-radius: 10px;\n"
"background-color: rgb(72, 81, 62);\n"
"color:rgb(255, 255, 255);\n"
"\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_3.addWidget(self.pushButton_8)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setStyleSheet("border-radius: 10px;\n"
"border: 3px solid rgb(230, 231, 197);\n"
"background-color: rgb(255, 255, 255);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout.addWidget(self.textEdit_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 666, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuFile_Properties = QtWidgets.QMenu(self.menu)
        self.menuFile_Properties.setObjectName("menuFile_Properties")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menu_4)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.menubar)
        self.menu_6.setObjectName("menu_6")
        self.menu_7 = QtWidgets.QMenu(self.menubar)
        self.menu_7.setObjectName("menu_7")
        MainWindow.setMenuBar(self.menubar)
        self.actionRemove_BOM = QtWidgets.QAction(MainWindow)
        self.actionRemove_BOM.setEnabled(False)
        self.actionRemove_BOM.setObjectName("actionRemove_BOM")
        self.actionCode_UTF_8 = QtWidgets.QAction(MainWindow)
        self.actionCode_UTF_8.setObjectName("actionCode_UTF_8")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.actionPower_saving_mode = QtWidgets.QAction(MainWindow)
        self.actionPower_saving_mode.setCheckable(True)
        self.actionPower_saving_mode.setObjectName("actionPower_saving_mode")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.actionSelect_All = QtWidgets.QAction(MainWindow)
        self.actionSelect_All.setEnabled(False)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionBug_submit = QtWidgets.QAction(MainWindow)
        self.actionBug_submit.setObjectName("actionBug_submit")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setCheckable(True)
        self.action_9.setChecked(True)
        self.action_9.setEnabled(False)
        self.action_9.setObjectName("action_9")
        self.action_10 = QtWidgets.QAction(MainWindow)
        self.action_10.setObjectName("action_10")
        self.action_11 = QtWidgets.QAction(MainWindow)
        self.action_11.setObjectName("action_11")
        self.action_12 = QtWidgets.QAction(MainWindow)
        self.action_12.setObjectName("action_12")
        self.action_13 = QtWidgets.QAction(MainWindow)
        self.action_13.setObjectName("action_13")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.menuFile_Properties.addAction(self.actionRemove_BOM)
        self.menuFile_Properties.addAction(self.actionCode_UTF_8)
        self.menu.addAction(self.menuFile_Properties.menuAction())
        self.menu.addAction(self.action)
        self.menu.addSeparator()
        self.menu.addAction(self.actionPower_saving_mode)
        self.menu_2.addAction(self.action_3)
        self.menu_2.addAction(self.action_4)
        self.menu_2.addAction(self.action_5)
        self.menu_3.addAction(self.actionSelect_All)
        self.menu_3.addAction(self.actionBug_submit)
        self.menu_5.addAction(self.action_9)
        self.menu_5.addAction(self.action_10)
        self.menu_5.addAction(self.action_11)
        self.menu_4.addAction(self.action_6)
        self.menu_4.addAction(self.action_7)
        self.menu_4.addAction(self.menu_5.menuAction())
        self.menu_4.addAction(self.action_12)
        self.menu_6.addAction(self.action_13)
        self.menu_7.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_6.menuAction())
        self.menubar.addAction(self.menu_7.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "大数逻辑运算（16进制）"))
        self.label_2.setText(_translate("MainWindow", "大数1："))
        self.label_6.setText(_translate("MainWindow", "大数2："))
        self.pushButton_5.setText(_translate("MainWindow", "异或运算"))
        self.pushButton_7.setText(_translate("MainWindow", "或运算"))
        self.pushButton_8.setText(_translate("MainWindow", "与运算"))
        self.textEdit_2.setPlaceholderText(_translate("MainWindow", "运算结果在这里"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menuFile_Properties.setTitle(_translate("MainWindow", "File Properties"))
        self.menu_2.setTitle(_translate("MainWindow", "视图"))
        self.menu_3.setTitle(_translate("MainWindow", "设置"))
        self.menu_4.setTitle(_translate("MainWindow", "界面跳转"))
        self.menu_5.setTitle(_translate("MainWindow", "大数运算单元"))
        self.menu_6.setTitle(_translate("MainWindow", "导航"))
        self.menu_7.setTitle(_translate("MainWindow", "帮助"))
        self.actionRemove_BOM.setText(_translate("MainWindow", "Remove BOM"))
        self.actionCode_UTF_8.setText(_translate("MainWindow", "Code:UTF-8"))
        self.action.setText(_translate("MainWindow", "退出"))
        self.actionPower_saving_mode.setText(_translate("MainWindow", "Power saving mode"))
        self.action_3.setText(_translate("MainWindow", "最小化"))
        self.action_4.setText(_translate("MainWindow", "最大化"))
        self.action_5.setText(_translate("MainWindow", "还原窗口"))
        self.actionSelect_All.setText(_translate("MainWindow", "Select All\n"
""))
        self.actionBug_submit.setText(_translate("MainWindow", "Bug submit"))
        self.action_6.setText(_translate("MainWindow", "哈希函数算子"))
        self.action_7.setText(_translate("MainWindow", "随机数生成"))
        self.action_9.setText(_translate("MainWindow", "大数逻辑运算"))
        self.action_10.setText(_translate("MainWindow", "大数算数运算"))
        self.action_11.setText(_translate("MainWindow", "大数模运算"))
        self.action_12.setText(_translate("MainWindow", "椭圆曲线算子"))
        self.action_13.setText(_translate("MainWindow", "返回"))
        self.action_2.setText(_translate("MainWindow", " 帮助文档"))
