# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Get_Rand_Digit.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(599, 462)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgba(0,52,48,230);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setStyleSheet("border-radius: 10px;\n"
"border: 3px solid rgb(230, 231, 197);\n"
"background-color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_2.addWidget(self.textBrowser)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 45))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "EZUSB-0")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 45))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setMinimumSize(QtCore.QSize(50, 0))
        self.comboBox_2.setBaseSize(QtCore.QSize(0, 0))
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(130, 30))
        self.pushButton.setStyleSheet("#pushButton{\n"
"\n"
"background-color: rgb(230, 231, 197);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#pushButton:hover{\n"
"border: 1px solid rgb(230, 231, 197);\n"
"border-radius: 10px;\n"
"background-color: rgb(72, 81, 62);\n"
"color:rgb(255, 255, 255);\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(130, 30))
        self.pushButton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
"\n"
"background-color: rgb(230, 231, 197);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#pushButton_2:hover{\n"
"border: 1px solid rgb(230, 231, 197);\n"
"border-radius: 10px;\n"
"background-color: rgb(72, 81, 62);\n"
"color:rgb(255, 255, 255);\n"
"\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(130, 30))
        self.pushButton_3.setStyleSheet("#pushButton_3{\n"
"\n"
"background-color: rgb(230, 231, 197);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#pushButton_3:hover{\n"
"border: 1px solid rgb(230, 231, 197);\n"
"border-radius: 10px;\n"
"background-color: rgb(72, 81, 62);\n"
"color:rgb(255, 255, 255);\n"
"\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 599, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuFile_Properties = QtWidgets.QMenu(self.menu)
        self.menuFile_Properties.setObjectName("menuFile_Properties")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menu_4)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.menubar)
        self.menu_6.setObjectName("menu_6")
        self.menu_7 = QtWidgets.QMenu(self.menubar)
        self.menu_7.setObjectName("menu_7")
        MainWindow.setMenuBar(self.menubar)
        self.actionRemove_BOM = QtWidgets.QAction(MainWindow)
        self.actionRemove_BOM.setEnabled(False)
        self.actionRemove_BOM.setObjectName("actionRemove_BOM")
        self.actionCode_UTF_8 = QtWidgets.QAction(MainWindow)
        self.actionCode_UTF_8.setObjectName("actionCode_UTF_8")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.actionPower_saving_mode = QtWidgets.QAction(MainWindow)
        self.actionPower_saving_mode.setCheckable(True)
        self.actionPower_saving_mode.setObjectName("actionPower_saving_mode")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.actionSelect_All = QtWidgets.QAction(MainWindow)
        self.actionSelect_All.setEnabled(False)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionBug_submit = QtWidgets.QAction(MainWindow)
        self.actionBug_submit.setObjectName("actionBug_submit")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setCheckable(True)
        self.action_7.setChecked(True)
        self.action_7.setEnabled(False)
        self.action_7.setObjectName("action_7")
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setObjectName("action_9")
        self.action_10 = QtWidgets.QAction(MainWindow)
        self.action_10.setObjectName("action_10")
        self.action_11 = QtWidgets.QAction(MainWindow)
        self.action_11.setObjectName("action_11")
        self.action_12 = QtWidgets.QAction(MainWindow)
        self.action_12.setObjectName("action_12")
        self.action_13 = QtWidgets.QAction(MainWindow)
        self.action_13.setObjectName("action_13")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.menuFile_Properties.addAction(self.actionRemove_BOM)
        self.menuFile_Properties.addAction(self.actionCode_UTF_8)
        self.menu.addAction(self.menuFile_Properties.menuAction())
        self.menu.addAction(self.action)
        self.menu.addSeparator()
        self.menu.addAction(self.actionPower_saving_mode)
        self.menu_2.addAction(self.action_3)
        self.menu_2.addAction(self.action_4)
        self.menu_2.addAction(self.action_5)
        self.menu_3.addAction(self.actionSelect_All)
        self.menu_3.addAction(self.actionBug_submit)
        self.menu_5.addAction(self.action_9)
        self.menu_5.addAction(self.action_10)
        self.menu_5.addAction(self.action_11)
        self.menu_4.addAction(self.action_6)
        self.menu_4.addAction(self.action_7)
        self.menu_4.addAction(self.menu_5.menuAction())
        self.menu_4.addAction(self.action_12)
        self.menu_6.addAction(self.action_13)
        self.menu_7.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_6.menuAction())
        self.menubar.addAction(self.menu_7.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "设备名称"))
        self.comboBox.setItemText(1, _translate("MainWindow", "EZUSB-1"))
        self.comboBox.setItemText(2, _translate("MainWindow", "CYUSB-0"))
        self.comboBox.setItemText(3, _translate("MainWindow", "CYUSB-1"))
        self.comboBox.setItemText(4, _translate("MainWindow", "CYUSB-2"))
        self.label_2.setText(_translate("MainWindow", "需要读出的十六进制数"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "位"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "K位"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "M位"))
        self.pushButton.setText(_translate("MainWindow", "读出"))
        self.pushButton_2.setText(_translate("MainWindow", "清空"))
        self.pushButton_3.setText(_translate("MainWindow", "下载"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menuFile_Properties.setTitle(_translate("MainWindow", "File Properties"))
        self.menu_2.setTitle(_translate("MainWindow", "视图"))
        self.menu_3.setTitle(_translate("MainWindow", "设置"))
        self.menu_4.setTitle(_translate("MainWindow", "界面跳转"))
        self.menu_5.setTitle(_translate("MainWindow", "大数运算单元"))
        self.menu_6.setTitle(_translate("MainWindow", "导航"))
        self.menu_7.setTitle(_translate("MainWindow", "帮助"))
        self.actionRemove_BOM.setText(_translate("MainWindow", "Remove BOM"))
        self.actionCode_UTF_8.setText(_translate("MainWindow", "Code:UTF-8"))
        self.action.setText(_translate("MainWindow", "退出"))
        self.actionPower_saving_mode.setText(_translate("MainWindow", "Power saving mode"))
        self.action_3.setText(_translate("MainWindow", "最小化"))
        self.action_4.setText(_translate("MainWindow", "最大化"))
        self.action_5.setText(_translate("MainWindow", "还原窗口"))
        self.actionSelect_All.setText(_translate("MainWindow", "Select All\n"
""))
        self.actionBug_submit.setText(_translate("MainWindow", "Bug submit"))
        self.action_6.setText(_translate("MainWindow", "哈希函数算子"))
        self.action_7.setText(_translate("MainWindow", "随机数生成"))
        self.action_9.setText(_translate("MainWindow", "大数逻辑运算"))
        self.action_10.setText(_translate("MainWindow", "大数算数运算"))
        self.action_11.setText(_translate("MainWindow", "大数模运算"))
        self.action_12.setText(_translate("MainWindow", "椭圆曲线算子"))
        self.action_13.setText(_translate("MainWindow", "返回"))
        self.action_2.setText(_translate("MainWindow", "帮助文档"))
