# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Get_Elliptic_Operator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 516)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgba(0,52,48,230);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setStyleSheet("border-radius: 10px;\n"
"border: 3px solid rgb(230, 231, 197);\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(71, 28))
        self.pushButton.setMaximumSize(QtCore.QSize(142, 56))
        self.pushButton.setStyleSheet("#pushButton{\n"
"\n"
"background-color: rgb(230, 231, 197);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#pushButton:hover{\n"
"border: 1px solid rgb(230, 231, 197);\n"
"border-radius: 10px;\n"
"background-color: rgb(72, 81, 62);\n"
"color:rgb(255, 255, 255);\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(71, 28))
        self.pushButton_2.setMaximumSize(QtCore.QSize(142, 56))
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
"background-color: rgb(230, 231, 197);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#pushButton_2:hover{\n"
"border: 1px solid rgb(230, 231, 197);\n"
"border-radius: 10px;\n"
"background-color: rgb(72, 81, 62);\n"
"color:rgb(255, 255, 255);\n"
"\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_5.setText("")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setStyleSheet("border-radius: 10px;\n"
"border: 3px solid rgb(230, 231, 197);\n"
"background-color: rgb(255, 255, 255);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout.addWidget(self.textEdit_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuFile_Properties = QtWidgets.QMenu(self.menu)
        self.menuFile_Properties.setObjectName("menuFile_Properties")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menu_4)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.menubar)
        self.menu_6.setObjectName("menu_6")
        self.menu_7 = QtWidgets.QMenu(self.menubar)
        self.menu_7.setObjectName("menu_7")
        MainWindow.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.actionRemove_BOM = QtWidgets.QAction(MainWindow)
        self.actionRemove_BOM.setEnabled(False)
        self.actionRemove_BOM.setObjectName("actionRemove_BOM")
        self.actionCode_UTF_8 = QtWidgets.QAction(MainWindow)
        self.actionCode_UTF_8.setObjectName("actionCode_UTF_8")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.actionPower_saving_mode = QtWidgets.QAction(MainWindow)
        self.actionPower_saving_mode.setCheckable(True)
        self.actionPower_saving_mode.setObjectName("actionPower_saving_mode")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.actionSelect_All = QtWidgets.QAction(MainWindow)
        self.actionSelect_All.setEnabled(False)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionBug_submit = QtWidgets.QAction(MainWindow)
        self.actionBug_submit.setObjectName("actionBug_submit")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_8 = QtWidgets.QAction(MainWindow)
        self.action_8.setObjectName("action_8")
        self.action_10 = QtWidgets.QAction(MainWindow)
        self.action_10.setObjectName("action_10")
        self.action_11 = QtWidgets.QAction(MainWindow)
        self.action_11.setObjectName("action_11")
        self.action_12 = QtWidgets.QAction(MainWindow)
        self.action_12.setObjectName("action_12")
        self.action_13 = QtWidgets.QAction(MainWindow)
        self.action_13.setCheckable(True)
        self.action_13.setChecked(True)
        self.action_13.setEnabled(False)
        self.action_13.setObjectName("action_13")
        self.action_14 = QtWidgets.QAction(MainWindow)
        self.action_14.setObjectName("action_14")
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setObjectName("action_9")
        self.menuFile_Properties.addAction(self.actionRemove_BOM)
        self.menuFile_Properties.addAction(self.actionCode_UTF_8)
        self.menu.addAction(self.menuFile_Properties.menuAction())
        self.menu.addAction(self.action_4)
        self.menu.addSeparator()
        self.menu.addAction(self.actionPower_saving_mode)
        self.menu_2.addAction(self.action_3)
        self.menu_2.addAction(self.action_5)
        self.menu_2.addAction(self.action_6)
        self.menu_3.addAction(self.actionSelect_All)
        self.menu_3.addAction(self.actionBug_submit)
        self.menu_5.addAction(self.action_10)
        self.menu_5.addAction(self.action_11)
        self.menu_5.addAction(self.action_12)
        self.menu_4.addAction(self.action_7)
        self.menu_4.addAction(self.action_8)
        self.menu_4.addAction(self.menu_5.menuAction())
        self.menu_4.addAction(self.action_13)
        self.menu_6.addAction(self.action_14)
        self.menu_7.addAction(self.action_9)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_6.menuAction())
        self.menubar.addAction(self.menu_7.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "这里是明文(ascii)"))
        self.label_3.setText(_translate("MainWindow", "↓"))
        self.pushButton.setText(_translate("MainWindow", "加密"))
        self.label_4.setText(_translate("MainWindow", "↑"))
        self.pushButton_2.setText(_translate("MainWindow", "解密"))
        self.textEdit_2.setPlaceholderText(_translate("MainWindow", "这里是加密后的序列"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menuFile_Properties.setTitle(_translate("MainWindow", "File Properties"))
        self.menu_2.setTitle(_translate("MainWindow", "视图"))
        self.menu_3.setTitle(_translate("MainWindow", "设置"))
        self.menu_4.setTitle(_translate("MainWindow", "界面跳转"))
        self.menu_5.setTitle(_translate("MainWindow", "大数运算单元"))
        self.menu_6.setTitle(_translate("MainWindow", "导航"))
        self.menu_7.setTitle(_translate("MainWindow", "帮助"))
        self.action.setText(_translate("MainWindow", "打开"))
        self.action_2.setText(_translate("MainWindow", "保存"))
        self.actionRemove_BOM.setText(_translate("MainWindow", "Remove BOM"))
        self.actionCode_UTF_8.setText(_translate("MainWindow", "Code:UTF-8"))
        self.action_4.setText(_translate("MainWindow", "退出"))
        self.actionPower_saving_mode.setText(_translate("MainWindow", "Power saving mode"))
        self.action_3.setText(_translate("MainWindow", "最小化"))
        self.action_5.setText(_translate("MainWindow", "最大化"))
        self.action_6.setText(_translate("MainWindow", "还原窗口"))
        self.actionSelect_All.setText(_translate("MainWindow", "Select All\n"
""))
        self.actionBug_submit.setText(_translate("MainWindow", "Bug submit"))
        self.action_7.setText(_translate("MainWindow", "哈希函数算子"))
        self.action_8.setText(_translate("MainWindow", "随机数生成"))
        self.action_10.setText(_translate("MainWindow", "大数逻辑运算"))
        self.action_11.setText(_translate("MainWindow", "大数算数运算"))
        self.action_12.setText(_translate("MainWindow", "大数模运算"))
        self.action_13.setText(_translate("MainWindow", "椭圆曲线算子"))
        self.action_14.setText(_translate("MainWindow", "返回"))
        self.action_9.setText(_translate("MainWindow", "帮助文档"))
