# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'About.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(547, 395)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 541, 361))
        self.frame.setStyleSheet("#frame{\n"
"background-image: url(:/加载背景/背景2.png);\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setStyleSheet("")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setGeometry(QtCore.QRect(-1, 0, 541, 361))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_9.setStyleSheet("#frame_9{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.283582 rgba(0, 52, 48, 250), stop:1 rgba(255, 255, 255, 0));\n"
"border: 3px solid rgb(230, 231, 197);\n"
"\n"
"\n"
"}\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_31 = QtWidgets.QLabel(self.frame_9)
        self.label_31.setGeometry(QtCore.QRect(450, 30, 72, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(230, 231, 197);\n"
"font: 20pt \"黑体\";\n"
"")
        self.label_31.setObjectName("label_31")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.frame_9)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 70, 491, 281))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_33 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: rgb(230, 231, 197);\n"
"\n"
"")
        self.label_33.setObjectName("label_33")
        self.verticalLayout_4.addWidget(self.label_33)
        self.label_34 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: rgb(230, 231, 197);\n"
"\n"
"")
        self.label_34.setObjectName("label_34")
        self.verticalLayout_4.addWidget(self.label_34)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label.setStyleSheet("color: rgb(230, 231, 197);\n"
"\n"
"")
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.label_36 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color: rgb(230, 231, 197);\n"
"\n"
"")
        self.label_36.setObjectName("label_36")
        self.verticalLayout_4.addWidget(self.label_36)
        self.label_35 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: rgb(230, 231, 197);\n"
"\n"
"")
        self.label_35.setObjectName("label_35")
        self.verticalLayout_4.addWidget(self.label_35)
        self.label_38 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("color: rgb(230, 231, 197);\n"
"\n"
"")
        self.label_38.setObjectName("label_38")
        self.verticalLayout_4.addWidget(self.label_38)
        self.pushButton = QtWidgets.QPushButton(self.frame_9)
        self.pushButton.setGeometry(QtCore.QRect(510, 0, 31, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(230, 231, 197);\n"
"background-color: rgba(0, 255, 255, 0);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.frame_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 547, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_31.setText(_translate("MainWindow", "IP核"))
        self.label_33.setText(_translate("MainWindow", "安全加速引擎IP核"))
        self.label_34.setText(_translate("MainWindow", "Build #PY-228.5367.102, Built On July 15,2023"))
        self.label.setText(_translate("MainWindow", "You have a per petual fallback license for this versionSubscription is active"))
        self.label_36.setText(_translate("MainWindow", "Development 2023.7"))
        self.label_35.setText(_translate("MainWindow", "Version 1.3.0"))
        self.label_38.setText(_translate("MainWindow", "西安中朗智控科技有限公司"))
        self.pushButton.setText(_translate("MainWindow", "×"))
import 新建文本文档_rc
